language: ruby
rvm:
  - 2.6 
env:
  global:
    - JEKYLL_ENV=production

cache: bundler
before_install:
  - gem install bundler jekyll 

script:
  - echo "Invoking jekyll build"
  - jekyll build --destination _site
  - ls _site

deploy:
  provider: firebase
  token: $TRAVIS_TOKEN
  skip_cleanup: true
  local-dir: ./_site